### ISSUE TITLE
Not a real AES?

### ISSUE THREAD

**Issue by doegox** [msotoodeh/WhiteBoxCrypto#1]
Hi,
It appears your AES whitebox is not following the standard AES keyschedule.
You may be interested in our analysis of Kryptologik:
http://blog.quarkslab.com/differential-fault-analysis-on-white-box-aes-implementations.html

**Comment by msotoodeh** [comment]
Hi,
Your observation is correct. The code generator tool works in two modes: standard and proprietary. In the proprietary mode it loads the round keys normally and then transforms the round keys by hashing or encryption with a second key. I considered this as a good security improvements since it does not costs anything in term of generated code size and performance.
p.s. I am very impressed with your analysis and report. Well done.

**Comment by doegox** [comment]
Thank you for your explanations.
p.s. thanks :)
